### ISSUE TITLE
Pi cam 

### ISSUE THREAD

**Issue by xyllin995** [Sairakshith99/Drive-Focus#8]
When testing the code, the error comes: 
VIDIOC_STREAMON: Invalid argument; 

and when I want to use camera to test whether it can take picture or not the errors come out: 
mmal: mmal_VC_ component enable: failed to enable component: ENOSPC 
mmal: camera component couldn't be enabled 
mmal: main: Failed to create camera component
mmal: Failed to run camera app. Please check for firmware updates

**Comment by aenlina** [comment]
After reinstalling the operating system and not solving the problem, we thought it might be a hardware problem. At first we used camera module 3, then we tried to change the camera twice, the first one was camera module 1, but because we forgot to turn off the power when we plugged in the camera, the pin was burned out and could not be detected, so we changed the second camera, which is camera module 2, and it finally ran, problem solved successfully.
